config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'top_pages#index'
  resources :sessions
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :favorites
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  validates :title, presence: true,length: { maximum: 50 }
  validates :content, presence: true,length: { maximum: 600 }
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/movie.rb
class Movie < ApplicationRecord 
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
             uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :user_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:index, :show]
  before_action :correct_user, only: [:edit, :destroy]
# GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    unless current_user == nil
       @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    end
  end

  # GET /blogs/new
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        ConfirmationMailer.confirmation_mail(@blog).deliver
        format.html { redirect_to @blog, notice: '　新規投稿しました！' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: '編集しました！' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: '削除しました！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache, :user_id)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください！"
      redirect_to new_session_path
    end
  end

  def correct_user
    unless current_user.id == @blog.user_id
      flash[:danger] = "他人の投稿は編集できません！"
      redirect_to new_session_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def show
    @favorites = current_user.favorite_blogs
  end
  
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if current_user.id == @user.id
      if @user.update(user_params)
        redirect_to @user, notice: "プロフィールを編集しました！"
      else
        render 'edit'
      end
    else
      flash[:danger] = "他人のプロフィールは編集できません！"
      redirect_to new_session_path
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :user_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true ,url: choose_new_or_edit) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation"> 
      <h2><%= pluralize(blog.errors.count, "件のエラー") %> 以下を確認してください</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :blog_content %>
  </div>


  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url)if@blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-default" %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<div class = "form_page">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p>画像:<%= image_tag @blog.image.url %></p>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
　<%= form.submit "もどる", name: 'back' %>
<% end %>
</div>

app/views/blogs/edit.html.erb
<div class = "edit_page">
<h1>編集ページ</h1>
<%= render 'form', blog: @blog %>
<P class="btn btn-default btn-sm"><%= link_to '詳細を見る', @blog %></P>
<P class="btn btn-default btn-sm"><%= link_to '戻る', blogs_path %></P>
</div>

app/views/blogs/index.html.erb
<div class = "index_page">
<p id="notice"><%= notice %></p>

<h1>みんなの投稿</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td class="btn btn-default"><%= link_to '詳細をみる', blog %></td>
        <%if current_user.try(:id) == blog.user_id %>
        <td class="btn btn-default"><%= link_to '編集する', edit_blog_path(blog) %></td>
        <td class="btn btn-default"><%= link_to '削除する', blog, method: :delete, data: { confirm: '消してもええんか？' } %></td>
　　　　<% end %>      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="btn btn-default"><%= link_to '新規投稿', new_blog_path %></p>
</div>

app/views/blogs/new.html.erb
<div class = "center">
<h1>画像を投稿して共有しよう！</h1>

<%= render 'form', blog: @blog %>

<P class="btn btn-default btn-sm"><%= link_to '投稿一覧へ', blogs_path %></P>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>画像:</strong>
  <%= image_tag @blog.image.url if @blog.image.url %>
</p>

<p>
  <strong>ユーザー名:</strong>
  <%= @blog.user.name %>
</p>
<% unless current_user == nil %>
 <% unless @blog.user_id == current_user.id %>
   <% if @favorite.present? %>
     <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
   <% else %>
     <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
   <% end %>
 <% end %>
<% end %>
<%if current_user.try(:id) == @blog.user_id %>
<p class="btn btn-default"><%= link_to '編集する', edit_blog_path(@blog) %></p>
<%end%>
<p class="btn btn-default"><%= link_to '戻る', blogs_path %></p>

app/views/favorites/show.html.erb
<div class = "center">
<h1>お気に入り</h1>

  <% @favorites.each do |blog| %>
    <p>画像:<%= image_tag blog.image.url if blog.image.url %></p>
    <p>投稿者:<%= blog.user.name %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instarogram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="wrapper">
   <header>
    <h1 class = "logo">instarogram</h1>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <p id = "header_logo" class="btn btn-default"><%= link_to "プロフィール", user_path(current_user.id) %></p>
      <p id = "header_logo" class="btn btn-default"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></p>
    <% else %>
      <p id = "header_logo" class="btn btn-default"><%= link_to "サインアップ", new_user_path %></p>
      <p id = "header_logo" class="btn btn-default"><%= link_to "ログイン", new_session_path %></p>
    <% end %>
   </header>
    <%= yield %>
   <footer>
     <div class = "foorter_logo">
      <li>利用規約</li>
      <li>採用情報</li>
      <li>Indstarogramについて</li>
      <li>ヘルプ</li>
      <li class = "establishment">©2050-2088 Increments Inc.</li>
     </div>
   </footer>
  </div>
  </body>
</html>

app/views/top_pages/index.html.erb
<h1 class = "top_tarobook">Instarogramの世界へようこそ！</h1>


<p class = "top_heading">思い出を共有して、世界とつながろう！</p>
<button type="button" class="btn btn-default btn-lg btn-block" id ="top_button"><%= link_to 'Dive into instatarogram', blogs_path %></button>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation"> 
      <h2><%= pluralize(user.errors.count, "件のエラー") %> 以下を確認してください</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email %>
  </div>
  
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :user_image %>
    <%= image_tag(@user.user_image.url)if@user.user_image.url %>
    <%= form.file_field :user_image %>
    <%= form.hidden_field :user_image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class = "center">
<h1>プロフィール編集</h1>

<%= render 'form', user: @user %>

<p class="btn btn-default"><%= link_to 'プロフィール', @user %></p> 
</div>

app/views/users/new.html.erb
<div class = "center">
<h1>サインアップ</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件のエラー") %> 以下の内容を確認してください</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "アカウントを作成", class:"btn btn-default" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class = "center">
  
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>
  <strong>プロフィール画像:</strong>
  <%= image_tag @user.user_image.url if @user.user_image.url %>
</p>
<%unless current_user == nil %>
 <% if current_user.id == @user.id %>
 <P class="btn btn-default"><%= link_to '編集する', edit_user_path %></p>
 <P class="btn btn-default"><%= link_to 'お気に入り', favorite_path %></p>
 <% end %>
<% end %>
<P class="btn btn-default"><%= link_to '新規投稿', new_blog_path %></p>

</div>